### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-t-tests-p-values#1]
@sandrabosk 
Couldn't find the students_gpa.txt file, told the students to use the one in here https://online.stat.psu.edu/stat500/sites/stat500/files/data/student_gpa.txt

**Comment by ironhack-edu** [comment]
@haggarw3 please check this one - I thought we resolved this the other day? Thank you!

**Comment by ironhack-edu** [comment]
Close issue with [commit: 14cfb25125f79ed2fe4a0161ecfed5ca8d47906f](https://github.com/ironhack-labs/lab-t-tests-p-values/commit/14cfb25125f79ed2fe4a0161ecfed5ca8d47906f).
